### PR TITLE
update download link to latest version (1.5.1.0)

### PR DESCRIPTION
**Pull request by ldez**

### CODE REVIEW

**Comment by mfonville** [comment]
I made a fork at automatically parses and builds with the very latest downloadlink found on the android-studio website :) https://github.com/mfonville/android-studio ; builds @ https://launchpad.net/~maarten-fonville/+archive/ubuntu/android-studio

**Comment by PaoloRotolo** [comment]
@mfonville That's really nice :) Can we merge the 2 projects?

**Comment by mfonville** [comment]
@PaoloRotolo of course :-) if that is possible in some way
I did attach my server to daily run the configure script and check for updates and it automatically pushes new builds to my PPA. I am not sure how we could redirect or copy these builds for users of your existing users in an automatic way though. But for sure you could at those moments a stable-build is released copy it from my PPA to yours.

**Comment by PaoloRotolo** [comment]
Okay, I'll update my website as well writing that beta and canary builds are available on your PPA.

**Comment by mfonville** [comment]
@PaoloRotolo thanks! :-)

**Comment by franklinyu** [comment]
@mfonville I am not familiar with the packaging system; how does APT knows that there is an update when it `apt-get upgrade`? Does @PaoloRotolo need to manually push the updates to his PPA (so that end user see them)? If so, your script of fetching the latest version should not be in the PPA, but instead a separate cron job on your computer (or maybe some server).

**Comment by mfonville** [comment]
@franklinyu yes, @PaoloRotolo could indeed also run the script himself and push to his PPA :-)
but I have indeed a cronjob set-up on my server, so at that the moment the binaries should already be available in the PPA and availble to be copied, which is very probably faster and less effort for him.

**Pull request closed without merging**
