### PR TITLE
Update control

### PR DESCRIPTION
**Pull request by deadbaed**
get all libraries for building out of the box

### CODE REVIEW

**Comment by mfonville** [comment]
Wouldn't it be better to use a recommends instead of a dependency for these?

**Comment by mfonville** [comment]
I did integrate this into my fork at https://github.com/mfonville/android-studio ; builds @ https://launchpad.net/~maarten-fonville/+archive/ubuntu/android-studio

**Comment by ploctaux** [comment]
A needless fork, again...
Why don't you give back to the original repo, because it's quite popular and a lot of people use it.

--
Philippe Loctaux <phil@philippeloctaux.com>

**Comment by mfonville** [comment]
@ploctaux because there were no response to last suggestions anymore; PRs not getting merged; issues being adressed. And least of all no updates to either the script and the PPA for latest android studio versions anymore.
Many of those issues and FAQ entries were only resolvable by completely revamping the build structure and the way the PPA is maintained. Which is what I did, I set my personal server up to to directly provide new builds as soon as they are available.

**Comment by franklinyu** [comment]
I came across a dependency problem before I got through it with package `lib32stdc++6` only (as described [here in StackOverflow](http://stackoverflow.com/a/30067060)). I can verify that at least `lib32ncurses5`, `lib32z1` and `lib32z1-dev` is unnecessary to pass my "Unable to run `mksdcard` SDK tool" problem.

**Comment by mfonville** [comment]
@franklinyu thank you; I will update my scripts accordingly

**Comment by mfonville** [comment]
@franklinyu I thought that maybe you didn't need lib32* because you have e.g. zlib1g:i386 installed using multi-arch?

**Comment by franklinyu** [comment]
@mfonville No, I did not have `zlib1g:i386` installed; I have `zlib1g` (amd64) though (actually I believe it was installed by  `zlib1g-dev`). Tell me if I need to check something else, or do you want a list of all my packages?

**Comment by mfonville** [comment]
@franklinyu no, need to check the details I guess. For now we can be a bit conservative on dropping these dependencies too fast and recheck the dependencies in the future again.

**Comment by franklinyu** [comment]
@mfonville If (for example) `lib32z1` is removed from the dependency list in some version, what will happen when a user upgrade to that version? Would the dangling `lib32z1` be removed by `apt-get autoremove` (if there is no other package depending on it)?

**Comment by mfonville** [comment]
@franklinyu it will get suggested to be automatically removed, in apt all packages are marked as being installed by the user or whether to fulfill a dependency. It will tell the user it can run apt-get autoremove to cleanup. You can read more about it in the debian/apt documentation.

**Comment by deadbaed** [comment]
i think its good to close this now.

**Pull request closed without merging**
